### ISSUE TITLE
게임 코드가 돌아가지않아.. ㅠㅠ 세그먼트에러가 뜨네.

### ISSUE THREAD

**Issue by becxer** [becxer/algobattle#1]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a639f8 in vfprintf () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) 
(gdb) quit

**Comment by becxer** [comment]
이유찾음..char\* str ="string..."  이렇게 되있을때, strcat 하면 segmetation 에러남( 리눅스 기준)
왜냐하면, stack 에 지정된 스트링은 뒤에 붙일 메모리가 없기때문이다.
따라서 char str[100] 이렇게 해서 sprintf 를 하거나 strcat 으로 붙여주면 잘돌아감.
2일동안이나 삽질했네ㅋㅋㅋㅋㅋㅋ

**Comment by Jisu-Lee** [comment]
헐......그랬구나..어떻게 알아냈어요?? 짱이네요 ㅎㅎ

2015년 2월 6일 오후 1:23, hp100.net notifications@github.com님이 작성:
